# TODO: Add deployment stage
image: node:20.11.1

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - brokerService/node_modules/
    - oauthService/node_modules/
    - usersService/node_modules/

build:
  stage: build
  image: docker:25.0.3
  services:
    - name: docker:25.0.3-dind
      command: ["--host=tcp://0.0.0.0:2375"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "Building Docker images"
    - docker compose -f docker-compose.yml build
  only:
    - main

test:
  stage: test
  image: node:20.11.1
  script:
    - echo "Running tests"
    - npm run install-all
    - npm test
  only:
    - merge_requests
    - main
