version: "3.8"

services:
  broker-service:
    build: ./brokerService
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - USER_SOCKET_PORT=3003
      - ADSDB_USER="user"
      - ADSDB_HOST="postgres"
      - ADSDB_DB="database"
      - ADSDB_PASSWORD="password"
      - ADSDB_PORT=5432

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432
