services:
  broker-service:
    build: ./brokerService
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - ./brokerService/dev.env
    depends_on:
      postgres:
        condition: service_healthy

  user-service:
    build: ./usersService
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - ./usersService/dev.env
    depends_on:
      postgres:
        condition: service_healthy

  oauth-service:
    build: ./oauthService
    restart: unless-stopped
    ports:
      - 3002:3002
    env_file:
      - ./oauthService/dev.env
    depends_on:
      postgres:
        condition: service_healthy
