module.exports = [
   { name: "reportType", length: 4 },
   { name: "structureId", length: 20 },
   { name: "validityFlags", length: 16 },
   { name: "participantAddress", length: 24 },
   { name: "addressQualifier", length: 8 },
   { name: "estPositionReportTime", length: 16, omit: (bits) => bits[0] === "0" },
   { name: "positionReportTime", length: 16, omit: (bits) => bits[1] === "0" },
   { name: "velocityReportTime", length: 16, omit: (bits) => bits[2] === "0" },
   { name: "latitude", length: 24, omit: (bits) => bits[3] === "0", valid: (bits) => bits[0] === "1" },
   { name: "longitude", length: 24, omit: (bits) => bits[3] === "0", valid: (bits) => bits[0] === "1" },
   { name: "geometricAltitude", length: 24, omit: (bits) => bits[4] === "0", valid: (bits) => bits[1] === "1" },
   { name: "nsVelocity", length: 16, omit: (bits) => bits[5] === "0", valid: (bits) => bits[2] === "1" },
   { name: "ewVelocity", length: 16, omit: (bits) => bits[5] === "0", valid: (bits) => bits[2] === "1" },
   { name: "groundSpeedOnSurface", length: 8, omit: (bits) => bits[6] === "0", valid: (bits) => bits[3] === "1" },
   { name: "headingOnSurface", length: 8, omit: (bits) => bits[7] === "0", valid: (bits) => bits[4] === "1" },
   { name: "barometricAltitude", length: 24, omit: (bits) => bits[8] === "0", valid: (bits) => bits[5] === "1" },
   { name: "verticalRate", length: 16, omit: (bits) => bits[9] === "0", valid: (bits) => bits[6] === "1" },
   { name: "nic", length: 8, omit: (bits) => bits[10] === "0" },
   { name: "estimatedLatitude", length: 24, omit: (bits) => bits[11] === "0", valid: (bits) => bits[8] === "1" },
   { name: "estimatedLongitude", length: 24, omit: (bits) => bits[12] === "0", valid: (bits) => bits[8] === "1" },
   { name: "estimatedNsVelocity", length: 16, omit: (bits) => bits[13] === "0", valid: (bits) => bits[9] === "1" },
   { name: "estimatedEwVelocity", length: 16, omit: (bits) => bits[14] === "0", valid: (bits) => bits[9] === "1" },
   { name: "surveillanceStatus", length: 8, omit: (bits) => bits[15] === "0" },
   { name: "reportMode", length: 8, omit: (bits) => bits[16] === "0" },
]
